### ISSUE TITLE
454 mate pairs problem: exit with no error msg

### ISSUE THREAD

**Issue by melop** [ksahlin/BESST#54] opened 2017-02-25 09:52 UTC
Hello. I am using both Illumina and 454 mate pairs for scaffolding. The 454 library is used at pass 6 (7kb insert size). The strange thing is that the program exits with no obvious error message. The last line in the stdout is : Writing out scaffolding results for step 5  ... . And it seems that the files for step 5 are correctly written out.

I then tried using this bam file on its own as pass 1, the program scaffolded just fine. 

Does anyone have any idea on what's going on?

Thank you!
Ray

**Comment by ksahlin** [comment] 2017-02-26 00:47
This can for example happen if there is no more writable disc space where BESST writes its output. I've also run into other issues with remote servers the causes programs to "hang", which is outside the control of BESST.

Also, a bug with option `-q` (multiprocessing) is known to sometimes cause a hang in BESST. Let me know if you used the multiprocessing option. I will remove this option completely in the next commit.

If none of these suggestions are relevant I'm not sure what goes wrong. Can you given me the last couple of lines for the Statistics file?

**Comment by melop** [comment] 2017-02-26 10:32
Thanks for looking into this. I think we can safely exclude the first possibility - there is sufficient empty space left on the server (I am running many other instances of scaffolding and gapfilling at the same time, they finished ok). The stopping point is repeatable - always stopping at the 454 library, except when I put it as the first library.

I did not turn on the -q option for scaffolding.

Let me just attach the whole Statistics file as well as the stdout for you to look at. 
[besst454debug.zip](https://github.com/ksahlin/BESST/files/801861/besst454debug.zip)

It seems that library 6 (7kb 454 mate pair) didn't get read in correctly because besst doesn't report size distribution statistics etc.


Ray

**Comment by ksahlin** [comment] 2017-02-26 16:12
Thanks, I cannot figure out what is wrong from the output. You said that you're running many instances simultaneously. In order to rule out any server issues or writing to the same directories/space etc. Can you try removing (or relocating) all output for that particular run and restart it ? That would be a good first check. If it still hags at the same place we take it from there.

**Comment by melop** [comment] 2017-02-26 19:23
So the other besst runs are done in completely different working directories and run on different nodes. It's unlikely that they interfered with each other. I have already deleted the output folder and reran this for 3 times before I posted, and it always stops at the same position. I also performed the scaffolding from 2 different contig sets (soapdenovo and meraculous), and both of them stopped at this 454 library. If you want, I can upload all the bam and contig files for you to take a look at (they are very big though, several hundred GB). Or, you could provide me with a debug version of besst and I can send you the log?

**Comment by ksahlin** [comment] 2017-02-27 14:12
ok! So then it should definitely be the parsing of the 454 library. I haven't worked with them. Are they formatted the same way? That is, they are paired and mapped read pairs are reported in the same way as for the illumina read pairs? 

Can you try only scaffolding with the 454 lib and see if it stops immediately? If that is the case, can you upload one contig set and just the 454 bamfile for that contig set. I think that would be a good minimal data set to debug on. Maybe even a subset of that bam file would work if the bug is in the parsing.

**Comment by melop** [comment] 2017-02-27 14:22
Yes, I tried scaffolding only with the 454 library. It seems to finish successfully. 

See the log here: 
[Statistics.txt](https://github.com/ksahlin/BESST/files/803876/Statistics.txt)

I adjusted the mate orientation to RF, and mapped with BWA SAMPE. An example of the bam file is attached:

[example.sam.zip](https://github.com/ksahlin/BESST/files/803891/example.sam.zip)

Because I have included PE libraries for scaffolding, I'm wondering if that will increase RAM requirement for BESST, and whether BESST may have run out of RAM?

Ray

**Comment by melop** [comment] 2017-03-06 15:58
Hi Kristoffer, have you noticed anything weird about the SAM format I sent you?

Ray

**Comment by ksahlin** [comment] 2017-03-06 17:27
The RAM should not increase at each step as most previous library data are discarded before starting a new pass (i.e. the read alignments from previous library). 

I didn't notice anything weird in the sam format. If scaffolding with the library by itself finishes, it indicates that it's not the BAM file that causes this. I don't have anymore ideas. 

One way to include this library could be to map the 454 reads to the scaffolds created in pass 5. It's not the same as running all passes at once, but it doesn't necessarily have to be worse.

**Comment by melop** [comment] 2017-03-08 13:10
Hi Kristoffer.  
I made a mistake before about the library it stopped at. In fact it was not the 7kb library that got stuck, it was the 12kb library. When I ran with only this 12kb 454 library, it says: To few valid read alignments exists to compute mean and variance of library (need at least 1000 observations). Got only 334 valid alignments. Please specify -m and -s to the program. 
Printing out scaffolds produced in earlier steps...
terminating...
Number of initial contigs: 781568

The problem is that the initial contigs have a very small N50 (1.9kb), so there aren't enough long contigs to estimate the size distribution automatically for these long inserts. I think one solution would be to manually specify the distribution. However, is there a way to make BESST to take advantage of the scaffolds from the previous step to estimate the insert size for the next step? That seems to be more convenient.

**Comment by ksahlin** [comment] 2017-03-08 16:42
Not internally in BESST. But the most straightforward solution to this would be to map the larger read libraries to scaffolds created in the previous pass. 

I'm closing this issue now, but let me know if you run into other problems.

**Closed by ksahlin** 2017-03-08 16:42 UTC

**Comment by melop** [comment] 2017-03-09 17:22
Hi Kristoffer,

     indeed, after specifying -m and -s BESST ran till the end. But I think one problem is that if these 2 parameters are specified by hand, the PE contamination doesn't work?
     Is it possible then to specify -m and -s for only some libraries?

Ray

**Comment by ksahlin** [comment] 2017-03-09 17:33
The PE contamination should still work even after specifying -m and -s  (verify in the Statistics.tex). 
No, ints not possible the specify m and s for some libraries at the moment. but I'll consider implementing that.

**Comment by melop** [comment] 2017-03-09 17:48
Oh, ok, as long as the PE contamination detection still works then it should be fine. I got confused because on the github front page it says that "Do not specify -m and -s in this case as BESST has a relatively advanced inference of library characteristics (some of it from theory described in GetDistr )."
