### ISSUE TITLE
no improvement with BESST

### ISSUE THREAD

**Issue by macmanes** [ksahlin/BESST#21] opened 2015-09-07 13:57 UTC
I am trying to scaffold a genome with a set of PE reads, a 5kb and 10kb mate pair libraries. My N50 is no better than when I started, despite most of my reads mapping.  I am guessing this is operator error, but I do not know where to go.. 

I am running like this:  

```
/share/BESST/runBESST -c contigs.fa -f 500.bam 5kb.bam 10kb.bam -o besst --orientation fr rf rf
```

I have a lot of output, but I am guessing something below will help in understanding, maybe the  `Did not enter path seartching algorithm between scaffolds due to too small fraction of small scaffolds` statement.  Any help greatly appreciated. 

```
NR OF FISHY READ LINKS:  0
Number of USEFUL READS (reads mapping to different contigs uniquly):  81735962
Number of non unique reads (at least one read non-unique in read pair) that maps to different contigs (filtered out from scaffolding):  148603456
Reads with too large insert size from "USEFUL READS" (filtered out):  2022638
Number of duplicated reads indicated and removed:  38426510
Mean coverage before filtering out extreme observations =  34.8079086376
Std dev of coverage before filtering out extreme observations=  11.8678052206
Mean coverage after filtering =  34.7339188382
Std coverage after filtering =  11.7637370316
Length of longest contig in calc of coverage:  108580
Length of shortest contig in calc of coverage:  29663
Number of BWA buggy edges removed:  0
Number of fishy edges in G_prime 5188884
Total time for CreateGraph-module, iteration 2: 2490.86317086

0 link edges created.
Perform inference on scaffold graph...
Remove isolated nodes.
0 isolated contigs removed from graph.



 Searching for paths BETWEEN scaffolds



Did not enter path seartching algorithm between scaffolds due to too small fraction of small scaffolds, fraction were:  0.0
Nr of contigs left:  1327215.0 Nr of linking edges left: 2264316.0
Number of gaps estimated by GapEst-LP module pathgaps in this step is: 0
Time elapsed for making scaffolds, iteration 2: 47.9242899418
```

**Comment by ksahlin** [comment] 2015-09-07 14:14
Hi!

BESST will create scaffolds in each of the three steps, located in folder "besst/BESST_output/passX/" , X = 1,2,3 are they all the same size?

In the statistics.txt file there will be stats on how much is scaffolded and what the isize was estimated to etc. for each of the libraries. Please mail the Statistics.txt file to ksahlin@kth.se and I can see in more detail what is going on. Thanks for letting me know!

**Comment by macmanes** [comment] 2015-09-07 14:32
Yes, they are all basically the same size - the N50 of pass1 is 1nt larger than that of pass2 and pass3. I just sent email. Here are the assembly stats. 

```
n	n:1000	L50	LG50	NG50	min	N80	N50	N20	E-size	max	sum	name
1385918	398490	85807	24252	10726	1000	2962	6880	11670	8391	108656	1.749e9	pass1/Scaffolds_pass1.fa
1385918	398373	85774	24257	10724	1000	2962	6881	11670	8392	108656	1.749e9	pass2/Scaffolds_pass2.fa
1385918	398373	85774	24257	10724	1000	2962	6881	11670	8392	108656	1.749e9	pass3/Scaffolds_pass3.fa
1625706	413929	90001	26706	9806	1000	2757	6487	10806	7756	108580	1.704e9	../contigs.fa
```

**Comment by ksahlin** [comment] 2015-12-02 14:04
Hi,

I have wrote you a mail about what I think is the cause for this based on what I see from the Statistics.txt file you sent me. I will therefore close this issue.

**Closed by ksahlin** 2015-12-02 14:04 UTC
